### ISSUE TITLE
Tutorial: contactLoader returns a wrapped object, not clear why

### ISSUE THREAD

**Issue by zspitz** [remix-run/react-router-website#112]
The first loader [introduced in the tutorial](https://reactrouter.com/en/main/start/tutorial#loading-data) returns `contacts` wrapped in an object.

```js
export async function loader() {
  const contacts = await getContacts();
  return { contacts };
}
```

which is then destructured from `useLoaderData`:

```js
const { contacts } = useLoaderData();
```

Why not return `contacts` directly from the loader?

---

Same for [creating a contact](https://reactrouter.com/en/main/start/tutorial#creating-contacts), [getting a contact](https://reactrouter.com/en/main/start/tutorial#url-params-in-loaders)

**Comment by brookslybrand** [comment]
@zspitz it's just a preference, you can do either one.

Many people like to return an object because it's easy to add more data later

By the way, if you have feedback or corrections to the docs, the [source is in the remix repo](https://github.com/remix-run/remix/tree/main/docs)
