### ISSUE TITLE
Tutorial: throwing a Response

### ISSUE THREAD

**Issue by zspitz** [remix-run/react-router-website#113]
In the [**Not found data** section](https://reactrouter.com/en/main/start/tutorial#not-found-data), when the parameter doesn't match a contact, you suggest `throw`ing a `Response` object:

```js
throw new Response("", {
  status: 404,
  statusText: "Not Found",
});
```

Is there any specific reason not to `throw` a simple `Error` object:

```js
throw new Error('No contact found')
```

which is [generally preferable](https://typescript-eslint.io/rules/only-throw-error/)?

---

The same throwing of a `Response` can also be seen in the [`useLoader` documentation](https://reactrouter.com/en/main/route/loader#throwing-in-loaders).

**Comment by mcansh** [comment]
throwing a response will render your nearest ErrorBoundary and all you to check the status code and render a 404 (or other status code specific) page instead of rendering a more generic error screen
