### ISSUE TITLE
404 for `/en/hooks/use-location`

### ISSUE THREAD

**Issue by leventebalogh** [remix-run/react-router-website#149]
### What is the problem?

When navigating to https://reactrouter.com/en/6.28.0/hooks/use-location (e.g. from the [source code](https://github.com/grafana/scenes/blob/leventebalogh/update-react-router/node_modules/react-router-dom/node_modules/react-router/dist/lib/hooks.d.ts#L28)), then I am redirected to the `/en` locale, which shows a 404. 

If I visit `https://reactrouter.com/6.28.0/hooks/use-location` directly, then all is good.

**Comment by zettca** [comment]
It's not just `use-location`, all the migration warning links redirect to `/en` and renders `404` too.

> React Router Future Flag Warning: React Router will begin wrapping state updates in `React.startTransition` in v7. You can use the `v7_startTransition` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_starttransition.

**Comment by brookslybrand** [comment]
Ugh, so sorry about that @leventebalogh and @zettca. We had some bad logic that wasn't parsing old urls correctly. I believe it's fixed now but please comment or open a new issue if you still notice 404s like this
