### ISSUE TITLE
[Bug]: Docs are not working (Something went wrong)

### ISSUE THREAD

**Issue by Newbie012** [remix-run/react-router-website#27]
### What version of React Router are you using?

docs

### Steps to Reproduce

1. navigate to https://reactrouter.com/
2. click on any link
3. click on go back (browser)

### Expected Behavior

should not crash

### Actual Behavior

![image](https://user-images.githubusercontent.com/10504365/210359651-3a102361-22f9-45d3-ac3c-a23d86f9bf28.png)

Happens not only to me.

**Comment by bobziroll** [comment]
Relevant conversation here: https://canary.discord.com/channels/770287896669978684/770287896669978687/1059908806869524491

Appears to be an issue with the `count` value not coming through correctly, as mentioned in the DIscord convo.
