### ISSUE TITLE
It would be nice to know where you are using the side navigation when reading a docs page.

### ISSUE THREAD

**Issue by motdde** [remix-run/react-router-website#62]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/12215060/235555588-c4da9a0b-1fb1-4def-aace-366541f74ef0.png">

In this case, the nested route on the list on the right should be either highlighted or underlined.

I have yet to try Remix, but this would be an excellent PR to get my feet wet.

Is anyone working on this?

**Comment by machour** [comment]
@motdde as far as I know, no one is working on this at the moment. Feel free to submit a pull request 🙌🏼

**Comment by motdde** [comment]
@hanny21 Please go ahead. I haven't got the bandwidth to try Remix.

Thanks @machour

**Comment by sandeepdotcode** [comment]
I noticed this issue while learning router from the tutorial, came here and found this issue has been open for a few months now.

@hankadev , are you still working on it or do you mind if I give it a try?

**Comment by hankadev** [comment]
@sandeepdotcode feel free to give it a try.. unfortunately I did not had time to finish it due to my workload.
