### ISSUE TITLE
issue with example We have an example for this: https://github.com/remix-run/react-router/tree/dev/examples/auth

### ISSUE THREAD

**Issue by uyriq** [remix-run/react-router-website#68]
We have an example for this: https://github.com/remix-run/react-router/tree/dev/examples/auth

_Originally posted by @timdorr in https://github.com/remix-run/react-router/issues/10206#issuecomment-1470267119_
            

Sorry, not shure is there a bug or stackblitz fault, but 
```success Install finished in 25.031s
$ vite
failed to load config from /home/projects/mkligxplv.github/vite.config.ts
error when starting dev server:
Error: The package "@esbuild/linux-x64" could not be found, and is needed by esbuild.
```
on https://stackblitz.com/github/remix-run/react-router/tree/main/examples/auth?file=src%2FApp.tsx

**Comment by timdorr** [comment]
The package-lock.json files need to be updated. This doesn't need to be fixed in this repo. It needs to happen in the main repo in the various example folders.

**Comment by uyriq** [comment]
@timdorr, you are right, just delete package-lock file fix all!
![image](https://github.com/remix-run/react-router-website/assets/105006434/54e75e55-4cde-4cf7-92a1-f3ccd2ee919a)
+ for advice!
