### ISSUE TITLE
[Feature Request]: Add 'Copy' Button to Code Samples in Documentation

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [remix-run/react-router-website#70]
**Description:**

I'd like to propose a feature for the official React Router documentation website. While going through the various examples in the documentation, I noticed that there isn't a straightforward way to copy the code samples. 

**Feature Description:**

It would be extremely helpful if a 'Copy' button could be added to each of the code blocks within the documentation. This button would allow users to instantly copy the code samples to their clipboard, reducing the chance of copying errors and saving time.

**Benefits:**

- **Increased efficiency:** This feature would allow developers to easily copy and paste code into their IDE without needing to manually select and copy the code, saving time and effort.
- **Reduced error potential:** By enabling one-click copying, we can minimize the chance of copying errors that might occur when users manually select code blocks.
- **Improved user experience:** This feature would make the documentation more user-friendly and increase its utility for developers of all experience levels.

I believe this would be a valuable addition to the React Router documentation, and I'd be happy to discuss it further if needed.

**Comment by Youssef11296** [comment]
@Manuel-Suarez-Abascal, It's already there, as I can see here for example, https://remix.run/docs/en/2.0.0/hooks/use-location

**Comment by Youssef11296** [comment]
@Manuel-Suarez-Abascal, Is it what you asking for?
If not, kindly, share more details about which page you are talking about and more details if possible.

**Comment by Manuel-Suarez-Abascal** [comment]
@Youssef11296 Yes, that's exactly the request. I am closing this issue now 🚀
