### ISSUE TITLE
Possible security issue: //TARGET_URL/ results in 302 to target

### ISSUE THREAD

**Issue by craigsc** [remix-run/react-router-website#72]
Example: https://reactrouter.com//google.com/
Expectation: 404
Actual: 302 redirects to google.com

This is bad because a malicious actor can send links that look like official reactrouter.com pages but the end users get silently redirected to a possible malicious site owned by the sender

I haven't dug too much into this yet but also see that it affects the main remix.run site too - https://remix.run//google.com/

**Comment by mcansh** [comment]
one solution is to parse the request origin and redirect using an absolute url with the origin instead of using just the pathname

```diff
- throw redirect(url.pathname.slice(0, -1) + url.search);
+ throw redirect(url.origin + url.pathname.slice(0, -1) + url.search);
```
