### ISSUE TITLE
Please add full text search to the documentation

### ISSUE THREAD

**Issue by raed667** [remix-run/react-router-website#75]
Adding search to reactrouter.com would significantly reduce time spent looking for the correct function / component

**Comment by Youssef11296** [comment]
@raed667, Lemme check

**Comment by Youssef11296** [comment]
@raed667, Bro, can you explain on which page of the docs you mean?
Is it this one, https://reactrouter.com/en/main ??

**Comment by IanVS** [comment]
Yes, it should search all the pages of reactrouter.com.
