### ISSUE TITLE
Issue on running in the dev mode using the "npm run dev" script.

### ISSUE THREAD

**Issue by Youssef11296** [remix-run/react-router-website#77]
It's complaining about the node:child_process, "Error: Cannot find module 'node:child_process'".

**Comment by brookslybrand** [comment]
Hey @Youssef11296, sorry no one ever responded to you. It looks like you might not have been on the right version of node, but I'm not 100% sure.

If that was the issue, as of #103 we have a `.nvmrc` file. So if you're using `nvm` you can just run

```sh
nvm use
```

to use the correct version of node
