### ISSUE TITLE
[Docs]: Documentation Light/Dark Theme

### ISSUE THREAD

**Issue by majamarijan** [remix-run/react-router-website#79]
### Describe what's incorrect/missing in the documentation

I noticed some misbehavior in the functionality when changing themes in React Router Docs. 
The theme is changing back or back and forth between dark/light when you:

1. click on the theme icon and change the theme and then immediately click on the h2 (for example in the Tutorial page heading with the id="data-writes--html-forms") or
2.  clicking on the empty space between the main text and the sidebar with the headings 

This is checked on both Chrome (Version 118.0.5993.117 ) and Firefox (Version 118.0.5993.117 ) <br />

![changeThemeProblem](https://github.com/remix-run/react-router/assets/98489426/6ef3a8ae-87fb-4be3-a466-915707c0daee)

**Comment by brookslybrand** [comment]
@majamarijan sorry no one ever got back to you on this

I've been spending some time cleaning up issues and updating the website. Is this still happening for you? I was unable to reproduce

**Comment by majamarijan** [comment]
Hi @brookslybrand! Yes, it is better (Chrome and Firefox), but the issue still exists => when change the theme and then click on the bookmark. 

Clicking on the blank space on the page doesn't affect the theme anymore.  That's corrected well!

![themeChangingProblem](https://github.com/remix-run/react-router-website/assets/98489426/8f41f021-964a-4404-8ad3-cf4848f44c03)

**Comment by brookslybrand** [comment]
@majamarijan, are you toggling your network speed or anything? I'm wondering if the action is getting cancelled before the cookie has a chance to update?

**Comment by majamarijan** [comment]
@brookslybrand , no toggling. Yeah, I think that's the problem. If the theme is changed, and I click on the bookmark in a half a second or less after changing the theme, then this happens. Yet, it is now much better than before.
