### ISSUE TITLE
Add search to the docs

### ISSUE THREAD

**Issue by brookslybrand** [remix-run/react-router-website#92]
Remix uses [DocSearch](https://docsearch.algolia.com/) by Algolia. Might be easiest just to copy this

**Comment by lachieh** [comment]
Duplicate of #75. There's also a thread that has been open for over 2 years in the discussions section of the react-router repo: https://github.com/remix-run/react-router/discussions/9846

**Comment by brookslybrand** [comment]
You're right, thanks @lachieh, this is a duplicate. Closing this and will address #75 with the fix
